### ISSUE TITLE
BMA423 initial configuration error

### ISSUE THREAD

**Issue by Muralimediot** [BoschSensortec/BMA423-Sensor-API#1]
Hello,

          I am trying to interface BMA423 with CC2650 launchpad and the connection is correct and the chip ID read and initialization process done well . After that in the "bma423_write_config_file" I am getting the initialization error. particularly from the function "bma4_read_regs" 

/* Read the status of config stream operation */
rslt |= bma4_read_regs(BMA4_INTERNAL_STAT, &config_stream_status, 1, dev);

**Result for the rslt = 0x00;**

if (config_stream_status != BMA4_ASIC_INITIALIZED) {
	rslt |= BMA4_E_CONFIG_STREAM_ERROR;
}
**Result for the above condition is rslt = 0x08**

In the Console I am getting "Initialization failed"

Here with I have attached the code for the same for reference.
Kindly help me to resolve the issue.

Thanks,
Murali.M
[i2c_test1_BMA_chipID_read.zip](https://github.com/BoschSensortec/BMA423-Sensor-API/files/2194682/i2c_test1_BMA_chipID_read.zip)

**Comment by BoschSensortec** [comment]
Hi @Muralimediot,

What is the chip_id read after the bma423 init?

**Comment by BoschSensortec** [comment]
Also, in the `USER_i2c_write` function, the `i2cTrans.readCount` should be 0.

**Comment by Muralimediot** [comment]
Hello,

Thanks for the reply. The chip_id after the bma423_init is 0x13, and I have changed the code for the USER_i2c_write function as you said the i2cTranslreadCount = 0. Even-though the initialization error is occurring.  

/* Read the status of config stream operation */
rslt |= bma4_read_regs(BMA4_INTERNAL_STAT, &config_stream_status, 1, dev);

**Result for the rslt = 0x00;**
[i2c_test1_BMA_init_config.zip](https://github.com/BoschSensortec/BMA423-Sensor-API/files/2196689/i2c_test1_BMA_init_config.zip)

if (config_stream_status != BMA4_ASIC_INITIALIZED) {
rslt |= BMA4_E_CONFIG_STREAM_ERROR;
}

**Result for the above condition is rslt = 0x08**

Here with I have attached the modified code for your reference.

Kindly help me to resolve this issue.

Thanks and Regards,
Murali M

**Comment by liuchengvbl** [comment]
The same error occured in my code, and I have found the question. I think it's the config_file which matters. 

In the initialization,  "bma423_write_config_file" (in "bma423.c") calls "bma4_write_config_file"( in "bma4.c") . The loop starts from 0, ends with BMA4_CONFIG_STREAM_SIZE:

	/* Write the config stream */
	for (index = 0; index < **BMA4_CONFIG_STREAM_SIZE**; index += dev->read_write_len)
			rslt |= stream_transfer_write((dev->config_file_ptr + index), index, dev);

BMA4_CONFIG_STREAM_SIZE is defined as 6144 (equal to the length of the bma423_config_file[]), while the BMA423_FEATURE_SIZE is defined as 64. The datasheet of BMA423 also indicate that the FEATURES_IN should have 64 bytes. But the loop above writes 6144 bytes into FEATURES_IN.

In addition, the bma423_config_file[] seems to have something wrong. I compared the array with the default value of FEATURES_IN in the datesheet, but found no similarity.

I tried a modification: 
1. Ues
    #define BMA4_CONFIG_STREAM_SIZE **UINT64_C(64)**
instead of UINT16_C(6144), in bma4_defs.h.
2. Set bma423_config_file[] to the default value of FEATURES_IN in the datesheet.
After that the problem is solved, the rslt is 0x00 after the config_file is written.

Hope it will help.

**Comment by lewisxhe** [comment]
I have encountered the same problem, accessing the 0x2A register after initializing the write configuration file. The same result is 0x00. There is no error in checking the read and write methods. It is likely that this is a problem with the BMA423 library. @BoschSensortec

**Comment by lewisxhe** [comment]
> I have encountered the same problem, accessing the 0x2A register after initializing the write configuration file. The same result is 0x00. There is no error in checking the read and write methods. It is likely that this is a problem with the BMA423 library. @BoschSensortec

I have found the problem, the external circuit connection caused the initialization to fail
